version: "3.8"

services:
  pong:
    container_name: pong-dev
    image: k4ran909/pong:nightly2
    volumes:
      #- ./data:/app/data
      - ../server:/app/server
      - ../db:/app/db
    ports:
      - "3001:3001" # <Host Port>:<Container Port>
      - "3307:3306"
